function changeimg(control,img,selected,iscard)
    {
    if(iscard==true)
        {
        $(control).parent().parent().css('background','url("/images/waiting.gif") no-repeat scroll 50%');
        $(control).parent().hide();
        $(control).css('filter','');
        $('<img/>').attr('src','/card.png?'+img).load(function()
            {
            $(this).remove();
            $(control).css('background','url("/card.png?'+img+'") no-repeat scroll 0px 0px');
            $(control).css('cursor','pointer');
            if(iscard==true)
                {
                $(control).css('cursor','pointer');
                if(selected==true)
                    {
                    $(control).hover(function()
                        {
                        $(control).removeClass("imgdes")
                    }
                    ,function()
                        {
                        $(control).removeClass("imgdes")
                    }
                    )
                }
                else
                    {
                    $(control).hover(function()
                        {
                        $(control).removeClass("imgdes")
                    }
                    ,function()
                        {
                        $(control).addClass("imgdes")
                    }
                    )
                }
                $(control).children().attr("data-tooltip",img);
                $(control).children().addClass("info");
                $(control).parent().parent().css('background','')
            }
            if(selected==true)
                {
                $(control).removeClass("imgdes")
            }
            else
                {
                $(control).addClass("imgdes")
            }
            $(control).parent().show();
            $('*[data-tooltip]').each(function(event)
                {
                $(this).qtip(
                    {
                    content:
                        {
                        text:function(event,api)
                            {
                            $.ajax(
                                {
                                url:'/helper/tooltip.php?'+api.elements.target.attr('data-tooltip')+'&'+classs
                            }
                            ).then(function(content)
                                {
                                api.set('content.text',content);
                                $('.tt_desc').slimScroll(
                                    {
                                    height:'150px',railVisible:true
                                }
                                )
                            }
                            ,function(xhr,status,error)
                                {
                                api.set('content.text',status+': '+error)
                            }
                            );
                            return'Loading...'
                        }
                    }
                    ,position:
                        {
                        viewport:$(window),my:'top center',at:'bottom center',effect:false
                    }
                    ,style:
                        {
                        classes:'qtip-bootstrap',width:380
                    }
                    ,hide:
                        {
                        fixed:true,delay:300
                    }
                }
                )
            }
            )
        }
        )
    }
    else
        {
        $(control).css('background','url("/card.png?'+img+'") no-repeat scroll 0px 0px');
        $(control).css('cursor','default');
        $(control).hover(function()
            {
            $(control).removeClass("imgdes")
        }
        ,function()
            {
            $(control).removeClass("imgdes")
        }
        );
        $(control).removeClass("imgdes");
        $(control).children().attr("data-tooltip","");
        $(control).children().removeClass("info")
    }
}
function setround()
    {
    if($("#card1").prop('selectedIndex')>0)
        {
        data[round][0][0]=$("#card1").val()
    }
    else
        {
        data[round][0][0]="";
        if(data[round][1][0]!=""&&data[round][1][0]!=null)
            {
            data[round][1][0]=""
        }
        if(data[round][3][0]!=""&&data[round][3][0]!=null)
            {
            data[round][3][0]=""
        }
    }
    if($("#card2").prop('selectedIndex')>0)
        {
        data[round][0][1]=$("#card2").val()
    }
    else
        {
        data[round][0][1]="";
        if(data[round][1][1]!=""&&data[round][1][1]!=null)
            {
            data[round][1][1]=""
        }
        if(data[round][3][1]!=""&&data[round][3][1]!=null)
            {
            data[round][3][1]=""
        }
    }
    if($("#card3").prop('selectedIndex')>0)
        {
        data[round][0][2]=$("#card3").val()
    }
    else
        {
        data[round][0][2]="";
        if(data[round][1][2]!=""&&data[round][1][2]!=null)
            {
            data[round][1][2]=""
        }
        if(data[round][3][2]!=""&&data[round][3][2]!=null)
            {
            data[round][3][2]=""
        }
    }
    if(((data[round][0][0]!=data[round][2][0])||data[round][0][0]=="")&&((data[round][0][1]!=data[round][2][0])||data[round][0][1]=="")&&((data[round][0][2]!=data[round][2][0])||data[round][0][2]==""))
        {
        data[round][2][0]="";
        data[round][2][1]="";
        data[round][2][2]=""
    }
}
function builddeck()
    {
    $('#deck').html("");
    var tempdata=[];
    var result;
    for(index=0;
    index<data.length;
    ++index)
        {
        if(index>0)
            {
            if(data[index][2][0]!=null&&data[index][2][0]!="")
                {
                result=-1;
                for(var i=0,len=tempdata.length;
                i<len;
                i++)
                    {
                    if(tempdata[i][0]===data[index][2][0])
                        {
                        result=i;
                        break
                    }
                }
                if(result>-1)
                    {
                    tempdata[result][3]=tempdata[result][3]+1
                }
                else
                    {
                    tempdata.push([data[index][2][0],data[index][2][1],data[index][2][2],1])
                }
            }
        }
    }
    tempdata.sort(function(a,b)
        {
        if(parseInt(a[1])==parseInt(b[1]))
            {
            if(a[2]<b[2])
                {
                return-1
            }
            else
                {
                return 1
            }
        }
        else
            {
            return parseInt(a[1],10)-parseInt(b[1],10)
        }
    }
    );
    for(index=0;
    index<tempdata.length;
    ++index)
        {
        if(tempdata[index]!=null)
            {
            if(tempdata[index][3]>1)
                {
                $('#deck').append('<div class="deck screenshot" rel="/card.png?'+tempdata[index][0]+'" data-count="'+tempdata[index][3]+'" data-name="'+tempdata[index][2]+'"><div class="pull-left deck-caption"><div class="deck-cost">'+tempdata[index][1]+'</div><div style="float:left;
                padding: 4px">'+tempdata[index][2]+' x '+tempdata[index][3]+'</div></div><div class="pull-right deck-pic" style="background: url(\'/card.png?'+tempdata[index][0]+'\');
                 background-repeat: no-repeat;
                 background-position: -50px -45px;
                "><div class="deck-fade"></div></div><div style="clear:both;
                "></div></div>')
            }
            else
                {
                $('#deck').append('<div class="deck screenshot" rel="/card.png?'+tempdata[index][0]+'" data-count="'+tempdata[index][3]+'" data-name="'+tempdata[index][2]+'"><div class="pull-left deck-caption"><div class="deck-cost">'+tempdata[index][1]+'</div><div style="float:left;
                padding: 4px">'+tempdata[index][2]+'</div></div><div class="pull-right deck-pic" style="background: url(\'/card.png?'+tempdata[index][0]+'\');
                 background-repeat: no-repeat;
                 background-position: -55px -45px;
                "><div class="deck-fade"></div></div><div style="clear:both;
                "></div></div>')
            }
        }
    }
    $(".deck").click(function()
        {
        var name=$(this).attr("data-name");
        var count=parseInt($(this).attr("data-count"));
        if(count>0)
            {
            count-=1;
            if(count>1)
                {
                $(this).children().children(":nth-child(2)").html(name+' x '+count)
            }
            else if(count==1)
                {
                $(this).children().children(":nth-child(2)").html(name)
            }
            else
                {
                $(this).addClass("imgdesb");
                $(this).children().children(":nth-child(2)").html(name)
            }
        }
        else
            {
            for(index=0;
            index<data.length;
            ++index)
                {
                if(index>0)
                    {
                    if(data[index][2][0]!=null&&data[index][2][0]!="")
                        {
                        if(data[index][2][2]==name)
                            {
                            count+=1
                        }
                    }
                }
            }
            $(this).removeClass("imgdesb");
            if(count>1)
                {
                $(this).children().children(":nth-child(2)").html(name+' x '+count)
            }
            else
                {
                $(this).children().children(":nth-child(2)").html(name)
            }
        }
        $(this).attr("data-count",count)
    }
    );
    $(".deck").hover(function()
        {
        var name=$(this).attr("data-name");
        for(index=0;
        index<data.length;
        ++index)
            {
            if(index>0)
                {
                if(data[index][2][0]!=null&&data[index][2][0]!="")
                    {
                    if(data[index][2][2]==name)
                        {
                        $('#round'+index).removeClass("imgdesb")
                    }
                    else
                        {
                        $('#round'+index).addClass("imgdesb")
                    }
                }
            }
        }
    }
    ,function()
        {
        $(".panel").children().removeClass("imgdesb")
    }
    )
}
function buildoverview()
    {
    for(index=0;
    index<data.length;
    ++index)
        {
        if(index>0)
            {
            var cont='';
            cont+='<div class="col-lg-14">#'+index+'</div>';
            if(data[index][3][0]!=null&&data[index][3][0]!="")
                {
                if(data[index][2][0]==data[index][0][0])
                    {
                    cont+='<div class="col-lg-13" ><div class="pull-left screenshot" rel="/card.png?'+data[index][0][0]+'"><b>'+data[index][3][0]+'</b></div><div class="pull-right" style="margin-left: 5px;
                    color: #CCCCCC;
                    ">|</div><div class="pull-right badge">'+data[index][1][0]+'</div></div>'
                }
                else
                    {
                    cont+='<div class="col-lg-13"><div class="pull-left screenshot grey" rel="/card.png?'+data[index][0][0]+'">'+data[index][3][0]+'</div><div class="pull-right" style="margin-left: 5px;
                    color: #CCCCCC;
                    ">|</div><div class="pull-right badge">'+data[index][1][0]+'</div></div>'
                }
            }
            else
                {
                cont+='<div class="col-lg-13">&nbsp;
                <div class="pull-right" style="margin-left: 5px;
                 color: #CCCCCC;
                ">|</div></div>'
            }
            if(data[index][3][1]!=null&&data[index][3][1]!="")
                {
                if(data[index][2][0]==data[index][0][1])
                    {
                    cont+='<div class="col-lg-13"><div class="pull-left screenshot" rel="/card.png?'+data[index][0][1]+'"><b>'+data[index][3][1]+'</b></div><div class="pull-right" style="margin-left: 5px;
                    color: #CCCCCC;
                    ">|</div><div class="pull-right badge">'+data[index][1][1]+'</div></div>'
                }
                else
                    {
                    cont+='<div class="col-lg-13"><div class="pull-left screenshot grey" rel="/card.png?'+data[index][0][1]+'">'+data[index][3][1]+'</div><div class="pull-right" style="margin-left: 5px;
                    color: #CCCCCC;
                    ">|</div><div class="pull-right badge">'+data[index][1][1]+'</div></div>'
                }
            }
            else
                {
                cont+='<div class="col-lg-13">&nbsp;
                <div class="pull-right" style="margin-left: 5px;
                 color: #CCCCCC;
                ">|</div></div>'
            }
            if(data[index][3][2]!=null&&data[index][3][2]!="")
                {
                if(data[index][2][0]==data[index][0][2])
                    {
                    cont+='<div class="col-lg-13"><div class="pull-left screenshot" rel="/card.png?'+data[index][0][2]+'"><b>'+data[index][3][2]+'</b></div><div class="pull-right badge">'+data[index][1][2]+'</div></div>'
                }
                else
                    {
                    cont+='<div class="col-lg-13"><div class="pull-left screenshot grey" rel="/card.png?'+data[index][0][2]+'">'+data[index][3][2]+'</div><div class="pull-right badge">'+data[index][1][2]+'</div></div>'
                }
            }
            else
                {
                cont+='<div class="col-lg-13">&nbsp;
                </div>'
            }
            cont+='<div style="clear:both;
            "></div>';
            $('#round'+index).html(cont);
            if(round==index)
                {
                $('#round'+index).css("background-color","#F2F2F2")
            }
            else
                {
                $('#round'+index).css("background-color","")
            }
        }
    }
}
function reload()
    {
}
function calculate()
    {
    keydown=false;
    var c1="";
    var c2="";
    var c3="";
    if($("#card1").prop('selectedIndex')>0)
        {
        c1=$("#card1").val()
    }
    if($("#card2").prop('selectedIndex')>0)
        {
        c2=$("#card2").val()
    }
    if($("#card3").prop('selectedIndex')>0)
        {
        c3=$("#card3").val()
    }
    jQuery.post("/helper/calculate.php",
        {
        c1:c1,c2:c2,c3:c3,round:round,data:JSON.stringify(data),options_mc:$('#options_mc').prop('checked'),options_cc:$('#options_cc').prop('checked'),options_other:$('#options_other').prop('checked'),options_profile:$('#options_profile').val()
    }
    ,function(d)
        {
        d=JSON.parse(d);
        data=d;
        if(data[0][0][0]=="success")
            {
            hearthpwn=data[0][0][7];
            if(data[round][0][0]!=""&&data[round][0][0]!=null)
                {
                $('#s1').html(data[round][1][0]+'<br>'+scorett(data[round][1][0]))
            }
            else
                {
                $('#s1').html("-<br>&nbsp;
                ")
            }
            if(data[round][0][1]!=""&&data[round][0][1]!=null)
                {
                $('#s2').html(data[round][1][1]+'<br>'+scorett(data[round][1][1]))
            }
            else
                {
                $('#s2').html("-<br>&nbsp;
                ")
            }
            if(data[round][0][2]!=""&&data[round][0][2]!=null)
                {
                $('#s3').html(data[round][1][2]+'<br>'+scorett(data[round][1][2]))
            }
            else
                {
                $('#s3').html("-<br>&nbsp;
                ")
            }
            builddeck();
            buildoverview();
            changecurve(1);
            screenshotPreview();
            if(data[0][0][4]!=null&&data[0][0][4]!="")
                {
                $('#dvalue').html(parseInt(data[0][0][4]))
            }
            else
                {
                $('#dvalue').html("0")
            }
            if(data[0][0][3]!=null&&data[0][0][3]!="")
                {
                if(data[0][0][3]['minion']!=null)
                    {
                    $('#dminion').html(parseInt(data[0][0][3]['minion']))
                }
                else
                    {
                    $('#dbattlecry').html("0")
                }
                if(data[0][0][3]['spell']!=null)
                    {
                    $('#dspell').html(parseInt(data[0][0][3]['spell']))
                }
                else
                    {
                    $('#dbattlecry').html("0")
                }
                if(data[0][0][3]['weapon']!=null)
                    {
                    $('#dweapon').html(parseInt(data[0][0][3]['weapon']))
                }
                else
                    {
                    $('#dbattlecry').html("0")
                }
                if(data[0][0][3]['battlecry']!=null)
                    {
                    $('#dbattlecry').html(parseInt(data[0][0][3]['battlecry']))
                }
                else
                    {
                    $('#dbattlecry').html("0")
                }
                if(data[0][0][3]['overload']!=null)
                    {
                    $('#doverload').html(parseInt(data[0][0][3]['overload']))
                }
                else
                    {
                    $('#doverload').html("0")
                }
                if(data[0][0][3]['taunt']!=null)
                    {
                    $('#dtaunt').html(parseInt(data[0][0][3]['taunt']))
                }
                else
                    {
                    $('#dtaunt').html("0")
                }
                if(data[0][0][3]['charge']!=null)
                    {
                    $('#dcharge').html(parseInt(data[0][0][3]['charge']))
                }
                else
                    {
                    $('#dcharge').html("0")
                }
                if(data[0][0][3]['secret']!=null)
                    {
                    $('#dsecret').html(parseInt(data[0][0][3]['secret']))
                }
                else
                    {
                    $('#dsecret').html("0")
                }
                if(data[0][0][3]['silence']!=null)
                    {
                    $('#dsilence').html(parseInt(data[0][0][3]['silence']))
                }
                else
                    {
                    $('#dsilence').html("0")
                }
                if(data[0][0][3]['spelldamage']!=null)
                    {
                    $('#dspelldamage').html(parseInt(data[0][0][3]['spelldamage']))
                }
                else
                    {
                    $('#dspelldamage').html("0")
                }
                if(data[0][0][3]['enrage']!=null)
                    {
                    $('#denrage').html(parseInt(data[0][0][3]['enrage']))
                }
                else
                    {
                    $('#denrage').html("0")
                }
                if(data[0][0][3]['deathrattle']!=null)
                    {
                    $('#ddeathrattle').html(parseInt(data[0][0][3]['deathrattle']))
                }
                else
                    {
                    $('#ddeathrattle').html("0")
                }
            }
            else
                {
                $('#dminion').html("0");
                $('#dspell').html("0");
                $('#dweapon').html("0");
                $('#dbattlecry').html("0");
                $('#doverload').html("0");
                $('#dtaunt').html("0");
                $('#dcharge').html("0");
                $('#dsecret').html("0");
                $('#dsilence').html("0");
                $('#dspelldamage').html("0");
                $('#denrage').html("0");
                $('#ddeathrattle').html("0")
            }
        }
        else
            {
        }
    }
    )
}
function selectround(roundvalue)
    {
    keydown=false;
    $("#card1,#card2,#card3").select2("val","default-grey").trigger("change");
    if(data[roundvalue][0][0]!=""&&data[roundvalue][0][0]!=null)
        {
        $("#card1").val(data[roundvalue][0][0]).trigger("change");
        if(data[roundvalue][2][0]==data[roundvalue][0][0])
            {
            changeimg('#img1',data[roundvalue][0][0],true,true)
        }
        else
            {
            changeimg('#img1',data[roundvalue][0][0],false,true)
        }
    }
    else
        {
        $("#card1").val("default-grey").trigger("change");
        changeimg('#img1','default-grey',false,false)
    }
    if(data[roundvalue][0][1]!=""&&data[roundvalue][0][1]!=null)
        {
        $("#card2").val(data[roundvalue][0][1]).trigger("change");
        if(data[roundvalue][2][0]==data[roundvalue][0][1])
            {
            changeimg('#img2',data[roundvalue][0][1],true,true)
        }
        else
            {
            changeimg('#img2',data[roundvalue][0][1],false,true)
        }
    }
    else
        {
        $("#card2").val("default-grey").trigger("change");
        changeimg('#img2','default-grey',false,false)
    }
    if(data[roundvalue][0][2]!=""&&data[roundvalue][0][2]!=null)
        {
        $("#card3").val(data[roundvalue][0][2]).trigger("change");
        if(data[roundvalue][2][0]==data[roundvalue][0][2])
            {
            changeimg('#img3',data[roundvalue][0][2],true,true)
        }
        else
            {
            changeimg('#img3',data[roundvalue][0][2],false,true)
        }
    }
    else
        {
        $("#card3").val("default-grey").trigger("change");
        changeimg('#img3','default-grey',false,false)
    }
    if(roundvalue==1)
        {
        $('#round').html(roundvalue+'/30')
    }
    else if(roundvalue==30)
        {
        $('#round').html(roundvalue+'/30')
    }
    else
        {
        $('#round').html(roundvalue+'/30')
    }
    $('.list-group-item').removeClass("active");
    $('#round'+roundvalue).addClass("active");
    if(data[roundvalue][1][0]!=""&&data[roundvalue][1][0]!=null)
        {
        $('#s1').html(data[roundvalue][1][0]+'<br>'+scorett(data[roundvalue][1][0]))
    }
    else
        {
        $('#s1').html("-<br>&nbsp;
        ")
    }
    if(data[roundvalue][1][1]!=""&&data[roundvalue][1][1]!=null)
        {
        $('#s2').html(data[roundvalue][1][1]+'<br>'+scorett(data[roundvalue][1][1]))
    }
    else
        {
        $('#s2').html("-<br>&nbsp;
        ")
    }
    if(data[roundvalue][1][2]!=""&&data[roundvalue][1][2]!=null)
        {
        $('#s3').html(data[roundvalue][1][2]+'<br>'+scorett(data[roundvalue][1][2]))
    }
    else
        {
        $('#s3').html("-<br>&nbsp;
        ")
    }
    buildoverview();
    window.location.hash=roundvalue
}
function isNumber(obj)
    {
    return!isNaN(parseFloat(obj))
}
function scorett(score)
    {
    if(isNumber(score)==true)
        {
        if($('#options_profile').val()!="trump"&&$('#options_profile').val()!="antigrav1ty")
            {
            if(score<15)
                {
                return"<small>"+tl['rating_never_pick']+"</small>"
            }
            else if(score>14&&score<30)
                {
                return"<small>"+tl['rating_terrible']+"</small>"
            }
            else if(score>29&&score<40)
                {
                return"<small>"+tl['rating_bad']+"</small>"
            }
            else if(score>39&&score<50)
                {
                return"<small>"+tl['rating_average']+"</small>"
            }
            else if(score>49&&score<60)
                {
                return"<small>"+tl['rating_above_average']+"</small>"
            }
            else if(score>59&&score<70)
                {
                return"<small>"+tl['rating_good']+"</small>"
            }
            else if(score>69&&score<80)
                {
                return"<small>"+tl['rating_great']+"</small>"
            }
            else if(score>79&&score<90)
                {
                return"<small>"+tl['rating_excellent']+"</small>"
            }
            else if(score>89)
                {
                return"<small>"+tl['rating_best']+"</small>"
            }
        }
        else
            {
            return""
        }
    }
    else
        {
        return""
    }
}
function changecurve(type)
    {
    if(type==1)
        {
        for(index=0;
        index<=7;
        ++index)
            {
            if(data[0][0][1]!=null&&data[0][0][1]!="")
                {
                if(data[0][0][1][index]!=null)
                    {
                    var height=(data[0][0][1][index]/10)*100;
                    if(height>100)
                        {
                        height=100
                    }
                    $('#mc'+index).children().children().animate(
                        {
                        height:height+"%"
                    }
                    );
                    $('#mc'+index+'a').html(data[0][0][1][index])
                }
                else
                    {
                    $('#mc'+index).children().children().animate(
                        {
                        height:"0%"
                    }
                    );
                    $('#mc'+index+'a').html("&nbsp;
                    ")
                }
            }
            else
                {
                $('#mc'+index).children().children().animate(
                    {
                    height:"0%"
                }
                );
                $('#mc'+index+'a').html("&nbsp;
                ")
            }
        }
        $('#curve_b').addClass("normal");
        $('#curve_s').removeClass("normal");
        $('#curve_m').removeClass("normal")
    }
    else if(type==2)
        {
        for(index=0;
        index<=7;
        ++index)
            {
            if(data[0][0][5]!=null&&data[0][0][5]!="")
                {
                if(data[0][0][5][index]!=null)
                    {
                    var height=(data[0][0][5][index]/10)*100;
                    if(height>100)
                        {
                        height=100
                    }
                    $('#mc'+index).children().children().animate(
                        {
                        height:height+"%"
                    }
                    );
                    $('#mc'+index+'a').html(data[0][0][5][index])
                }
                else
                    {
                    $('#mc'+index).children().children().animate(
                        {
                        height:"0%"
                    }
                    );
                    $('#mc'+index+'a').html("&nbsp;
                    ")
                }
            }
            else
                {
                $('#mc'+index).children().children().animate(
                    {
                    height:"0%"
                }
                );
                $('#mc'+index+'a').html("&nbsp;
                ")
            }
        }
        $('#curve_m').addClass("normal");
        $('#curve_s').removeClass("normal");
        $('#curve_b').removeClass("normal")
    }
    else if(type==3)
        {
        for(index=0;
        index<=7;
        ++index)
            {
            if(data[0][0][6]!=null&&data[0][0][6]!="")
                {
                if(data[0][0][6][index]!=null)
                    {
                    var height=(data[0][0][6][index]/10)*100;
                    if(height>100)
                        {
                        height=100
                    }
                    $('#mc'+index).children().children().animate(
                        {
                        height:height+"%"
                    }
                    );
                    $('#mc'+index+'a').html(data[0][0][6][index])
                }
                else
                    {
                    $('#mc'+index).children().children().animate(
                        {
                        height:"0%"
                    }
                    );
                    $('#mc'+index+'a').html("&nbsp;
                    ")
                }
            }
            else
                {
                $('#mc'+index).children().children().animate(
                    {
                    height:"0%"
                }
                );
                $('#mc'+index+'a').html("&nbsp;
                ")
            }
        }
        $('#curve_s').addClass("normal");
        $('#curve_b').removeClass("normal");
        $('#curve_m').removeClass("normal")
    }
}
$(document).ready(function()
    {
    $(".chosen-select").select2();
    if(data!=null&&data!="")
        {
        data=JSON.parse(data)
    }
    else
        {
        data=[[
            {
        }
        ,
            {
        }
        ,
            {
        }
        ,
            {
        }
        ],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]]];
        data[0][0][2]=classs
    }
    $("#card1").on("change",function(e)
        {
        if(keydown==true)
            {
            if($("#card1").prop('selectedIndex')>0)
                {
                changeimg('#img1',$(this).val(),false,true)
            }
            else
                {
                changeimg('#img1',$(this).val(),false,false);
                $('#s1').html("-<br>&nbsp;
                ")
            }
            $("#save").parent().removeClass('disabled');
            $('.popupDeck').hide();
            setround();
            calculate()
        }
    }
    );
    $("#card2").on("change",function(e)
        {
        if(keydown==true)
            {
            if($("#card2").prop('selectedIndex')>0)
                {
                changeimg('#img2',$(this).val(),false,true)
            }
            else
                {
                changeimg('#img2',$(this).val(),false,false);
                $('#s2').html("-<br>&nbsp;
                ")
            }
            $("#save").parent().removeClass('disabled');
            $('.popupDeck').hide();
            setround();
            calculate()
        }
    }
    );
    $("#card3").on("change",function(e)
        {
        if(keydown==true)
            {
            if($("#card3").prop('selectedIndex')>0)
                {
                changeimg('#img3',$(this).val(),false,true)
            }
            else
                {
                changeimg('#img3',$(this).val(),false,false);
                $('#s3').html("-<br>&nbsp;
                ")
            }
            $("#save").parent().removeClass('disabled');
            $('.popupDeck').hide();
            setround();
            calculate()
        }
    }
    );
    $("#card1").on("select2-close",function()
        {
        keydown=true
    }
    );
    $("#card2").on("select2-close",function()
        {
        keydown=true
    }
    );
    $("#card3").on("select2-close",function()
        {
        keydown=true
    }
    );
    $('#img1,#img2,#img3').click(function()
        {
        if($(this).attr("id")=="img1"&&$("#card1").prop('selectedIndex')<=0)
            {
            return false
        }
        if($(this).attr("id")=="img2"&&$("#card2").prop('selectedIndex')<=0)
            {
            return false
        }
        if($(this).attr("id")=="img3"&&$("#card3").prop('selectedIndex')<=0)
            {
            return false
        }
        if($("#card1").prop('selectedIndex')>0)
            {
            data[round][0][0]=$("#card1").val()
        }
        if($("#card2").prop('selectedIndex')>0)
            {
            data[round][0][1]=$("#card2").val()
        }
        if($("#card3").prop('selectedIndex')>0)
            {
            data[round][0][2]=$("#card3").val()
        }
        if($("#card1").prop('selectedIndex')>0||$("#card2").prop('selectedIndex')>0||$("#card3").prop('selectedIndex')>0)
            {
            if($(this).attr("id")=="img1")
                {
                data[round][2][0]=$("#card1").val()
            }
            if($(this).attr("id")=="img2")
                {
                data[round][2][0]=$("#card2").val()
            }
            if($(this).attr("id")=="img3")
                {
                data[round][2][0]=$("#card3").val()
            }
            round+=1;
            if(round>30)
                {
                round=1
            }
            calculate();
            selectround(round)
        }
    }
    );
    $('.roundselect').click(function()
        {
        round=parseInt($(this).attr('data-content'));
        selectround(round);
        screenshotPreview();
        $("[id=screenshot]").remove();
        $('#myTab a[href="#home"]').tab('show')
    }
    );
    $('#reset').click(function()
        {
        if(confirm('Are you sure?'))
            {
            round=1;
            data=[[
                {
            }
            ,
                {
            }
            ,
                {
            }
            ,
                {
            }
            ],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]],[[],[],[],[]]];
            data[0][0][2]=classs;
            var parts=location.hostname.split('.');
            var subdomain=parts.shift();
            if(subdomain=='arenavalue')
                {
                subdomain='www'
            }
            window.location.href='http://'+subdomain+'.arenavalue.com/'
        }
    }
    );
    $('.thermometer').thermometer();
    if(window.location.hash)
        {
        if(!isNaN(window.location.hash.substr(1)))
            {
            if(parseInt(window.location.hash.substr(1))>0&&parseInt(window.location.hash.substr(1))<31)
                {
                round=parseInt(window.location.hash.substr(1))
            }
        }
    }
    if(link)
        {
        $.getJSON('/helper/getdata.php?deck='+link,function(e)
            {
            data=e;
            calculate();
            selectround(round)
        }
        )
    }
    else
        {
        calculate();
        selectround(round)
    }
    $("#save").click(function(event)
        {
        if(!$(this).parent().hasClass("disabled"))
            {
            jQuery.post("/helper/save.php",
                {
                data:JSON.stringify(data),link:link
            }
            ,function(d)
                {
                try
                    {
                    d=JSON.parse(d);
                    if(d.status=="success")
                        {
                        var parts=location.hostname.split('.');
                        var subdomain=parts.shift();
                        if(subdomain=='arenavalue')
                            {
                            subdomain='www'
                        }
                        link=d.message;
                        $('.popupDeck').show();
                        window.history.pushState("object or string","Title","/s/"+d.message);
                        showInfo('Done... <a target="_blank" href="http://'+subdomain+'.arenavalue.com/s/'+d.message+'">http://'+subdomain+'.arenavalue.com/s/'+d.message+'</a>',"","","",1);
                        $("#save").parent().addClass('disabled')
                    }
                }
                catch(err)
                    {
                    alert(err)
                }
            }
            )
        }
    }
    );
    $("*[data-social]").click(function(event)
        {
        var parts=location.hostname.split('.');
        var subdomain=parts.shift();
        if(subdomain=='arenavalue')
            {
            subdomain='www'
        }
        var network=$(this).attr("data-social");
        if(network=="hearthpwn")
            {
            $(this).attr('href','http://www.hearthpwn.com/deckbuilder/'+hearthpwn)
        }
        else
            {
            if(link=="")
                {
                alert("Please save your deck!");
                return false
            }
            else
                {
                if(network=="reddit")
                    {
                    $(this).attr('href','http://www.reddit.com/submit?url='+encodeURIComponent('http://'+subdomain+'.arenavalue.com/s/'+link))
                }
                else if(network=="facebook")
                    {
                    $(this).attr('href','https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent('http://'+subdomain+'.arenavalue.com/s/'+link))
                }
                else if(network=="twitter")
                    {
                    $(this).attr('href','https://twitter.com/intent/tweet?url='+encodeURIComponent('http://'+subdomain+'.arenavalue.com/s/'+link))
                }
            }
        }
    }
    );
    $('#modal_options').on('hidden.bs.modal',function()
        {
        $('#dprofile').html($('#options_profile option:selected').text());
        calculate()
    }
    );
    $("#curve_m").click(function(event)
        {
        changecurve(2);
        $(this).blur();
        return false
    }
    );
    $("#curve_s").click(function(event)
        {
        changecurve(3);
        $(this).blur();
        return false
    }
    );
    $("#curve_b").click(function(event)
        {
        changecurve(1);
        $(this).blur();
        return false
    }
    );
    $("*[data-detail]").parent().hover(function(event)
        {
        var detail=$(this).children().attr("data-detail")+";
        ";
        $(this).css("font-weight","bold");
        $("#deck").children().each(function()
            {
            var name=$(this).attr("data-name");
            for(index=0;
            index<data.length;
            ++index)
                {
                if(index>0)
                    {
                    if(data[index][2][0]!=null&&data[index][2][0]!="")
                        {
                        if(name==data[index][2][2])
                            {
                            if(data[index][2][3].indexOf(detail)>=0)
                                {
                            }
                            else
                                {
                                $(this).addClass("imgdesb")
                            }
                        }
                    }
                }
            }
        }
        )
    }
    ,function()
        {
        $(this).css("font-weight","normal");
        $("#deck").children().each(function()
            {
            var name=$(this).attr("data-name");
            var count=parseInt($(this).attr("data-count"));
            if(count>0)
                {
                $(this).removeClass("imgdesb")
            }
            else
                {
                $(this).addClass("imgdesb")
            }
        }
        )
    }
    );
    $('*[data-toggle="tab"]').click(function(event)
        {
        if($(this).attr("href")=="#overview")
            {
            $("#deck").parent().addClass("deck-overview")
        }
        else
            {
            $("#deck").parent().removeClass("deck-overview")
        }
    }
    );
    $('#forward').click(function()
        {
        round+=1;
        if(round>30)
            {
            round=1
        }
        selectround(round);
        screenshotPreview()
    }
    );
    $('#back').click(function()
        {
        round-=1;
        if(round<1)round=30;
        selectround(round);
        screenshotPreview()
    }
    );
    $("#form_import").submit(function(event)
        {
        $(this).ajaxSubmit(
            {
            url:"/helper/import.php",dataType:"json",success:function(responseText,statusText,xhr,$form)
                {
                if(responseText.status!="success")
                    {
                    handleError(responseText,statusText)
                }
                if(responseText.status=="success")
                    {
                    data=responseText.data;
                    calculate();
                    selectround(1)
                }
            }
            ,error:showError
        }
        );
        $("#modal_import").modal("hide");
        event.preventDefault();
        return false
    }
    )
}
);
screenshotPreview=function()
    {
    xOffset=111;
    yOffset=10;
    $(".screenshot").hover(function(e)
        {
        this.t=this.title;
        this.title="";
        var c=(this.t!="")?"<br/>"+this.t:"";
        var cardsleft=0;
        var uniquecardsleft=0;
        $("#deck").children().each(function()
            {
            if(parseInt($(this).attr("data-count"))>0)
                {
                uniquecardsleft+=1
            }
            cardsleft+=parseInt($(this).attr("data-count"))
        }
        );
        var drawchance="";
        if(uniquecardsleft<30)
            {
            if($(this).attr("data-count"))
                {
                if(parseInt($(this).attr("data-count"))>0)
                    {
                    drawchance="<div class='pull-left' style='margin: -12px 0 0 7px ;
                     text-shadow: -1px 0 #FFFFFF, 0 1px #FFFFFF, 1px 0 #FFFFFF, 0 -1px #FFFFFF;
                    '>Probability of drawing:</div><div class='pull-right' style='margin: -12px 7px 0 0;
                     text-shadow: -1px 0 #FFFFFF, 0 1px #FFFFFF, 1px 0 #FFFFFF, 0 -1px #FFFFFF;
                    '>"+(Math.round(((1/cardsleft)*100)*100*parseInt($(this).attr("data-count")))/100)+"%</div>"
                }
                else
                    {
                    drawchance="<div class='pull-left' style='margin: -12px 0 0 7px ;
                     text-shadow: -1px 0 #FFFFFF, 0 1px #FFFFFF, 1px 0 #FFFFFF, 0 -1px #FFFFFF;
                    '>Probability of drawing:</div><div class='pull-right' style='margin: -12px 7px 0 0;
                     text-shadow: -1px 0 #FFFFFF, 0 1px #FFFFFF, 1px 0 #FFFFFF, 0 -1px #FFFFFF;
                    '>0%</div>"
                }
            }
        }
        if($('#id').length)
            {
            $('#id').html("<img src='"+$(this).attr('rel')+"' alt='url preview' />"+drawchance+"")
        }
        else
            {
            $("body").append("<div id='screenshot'><div><img src='"+$(this).attr('rel')+"' alt='url preview' /></div>"+drawchance+"</div>")
        }
        $("#screenshot").css("top",(e.pageY-xOffset)+"px").css("left",(e.pageX+yOffset)+"px").fadeIn("fast")
    }
    ,function()
        {
        this.title=this.t;
        $("[id=screenshot]").remove()
    }
    );
    $(".screenshot").mousemove(function(e)
        {
        $("#screenshot").css("top",(e.pageY-xOffset-$(window).scrollTop())+"px").css("left",(e.pageX+yOffset)+"px")
    }
    )
};
